#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TestFootballApi.Droid.Resource", IsApplication=true)]

namespace TestFootballApi.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmCross.Resource.Attribute.MvxBind = global::TestFootballApi.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Resource.Attribute.MvxDropDownItemTemplate = global::TestFootballApi.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Resource.Attribute.MvxGroupItemTemplate = global::TestFootballApi.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Resource.Attribute.MvxItemTemplate = global::TestFootballApi.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Resource.Attribute.MvxLang = global::TestFootballApi.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Resource.Attribute.MvxTemplate = global::TestFootballApi.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Resource.Id.MvvmCrossTagId = global::TestFootballApi.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Resource.Id.MvxBindingTagUnique = global::TestFootballApi.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Resource.Styleable.MvxBinding = global::TestFootballApi.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Resource.Styleable.MvxBinding_MvxBind = global::TestFootballApi.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Resource.Styleable.MvxBinding_MvxLang = global::TestFootballApi.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Resource.Styleable.MvxControl = global::TestFootballApi.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Resource.Styleable.MvxControl_MvxTemplate = global::TestFootballApi.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Resource.Styleable.MvxExpandableListView = global::TestFootballApi.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::TestFootballApi.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Resource.Styleable.MvxListView = global::TestFootballApi.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::TestFootballApi.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Resource.Styleable.MvxListView_MvxItemTemplate = global::TestFootballApi.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int MvxGroupItemTemplate = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f030000
			public const int MvvmCrossTagId = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int MvxBindingTagUnique = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int caption = 2130903042;
			
			// aapt resource value: 0x7f030005
			public const int gamesLayout = 2130903045;
			
			// aapt resource value: 0x7f03000c
			public const int listView = 2130903052;
			
			// aapt resource value: 0x7f030007
			public const int matchDayLayout = 2130903047;
			
			// aapt resource value: 0x7f030006
			public const int numberOfGames = 2130903046;
			
			// aapt resource value: 0x7f030008
			public const int numberOfMatchDays = 2130903048;
			
			// aapt resource value: 0x7f030004
			public const int numberOfTeams = 2130903044;
			
			// aapt resource value: 0x7f03000d
			public const int teamName = 2130903053;
			
			// aapt resource value: 0x7f030003
			public const int teamsLayout = 2130903043;
			
			// aapt resource value: 0x7f03000a
			public const int viewFixtures = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int viewTable = 2130903051;
			
			// aapt resource value: 0x7f030009
			public const int viewTeams = 2130903049;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int CompetitionDetailsView = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int competitionlistitemview = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int CompetitionsView = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int competitionteamlistitemview = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int CompetitionTeamsView = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Main = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int SplashScreen = 2130837510;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
